server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://hwehykgyouzccp:d00c8a3ba32f55b930417908c86fbba5edeac20568d972a7ffb7f4057c0a6936@ec2-3-215-57-87.compute-1.amazonaws.com:5432/d2m9u2nu960tf1
    username: hwehykgyouzccp
    password: d00c8a3ba32f55b930417908c86fbba5edeac20568d972a7ffb7f4057c0a6936
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-dll: true
    hibernate:
      dll-auto: none

application:
  description: Projeto criado para o bootcamp DIO / Santander
  version: 1.1.0